import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Full page max-width container */}
        <div className="max-w-[1920px] mx-auto bg-[#111]">
          {/* Navbar - transparent, shows body bg */}
          <NavBar />
          
          {/* Main content - individual sections have their own bg */}
          <main className="min-h-screen">
            {children}
          </main>

          {/* Footer - has its own bg */}
          <footer className="text-center bg-slate-600 py-4 text-white">
            Awesome Next.js Project
          </footer>
        </div>
      </body>
    </html>
  );
}
